### ISSUE TITLE
(emacs) org-roam upstream updated and causes error

### ISSUE THREAD

**Issue by qingshuizheng** [d12frosted/environment#14]
Hi Boris,

Currently using your great emacs configs and change as per my need. Love the way you use emacs.
It's been working well until 2 days ago org-roam upstream changed _org-roam--org-roam-file-p_ to _org-roam-file-p_, see here: [make some more functions public](https://github.com/org-roam/org-roam/commit/5224eb2c2ebce087abd6bdde8621a4f70cf2cec7#diff-2f1e3beb58c04fd0b840c2761afd33f1fddc1b6ef25860d52af87341c3392b51), then my org-roam broke down:

After running `eru.sh install emacs`, the compiler, linter are happy with everything, but got this at the end:

`[00:03.083]  Linter has no complaints
[00:03.083]  Finished successfully on Mon Jun 21 14:00:56 2021
eldev exec "(progn (run-hooks 'after-init-hook) (vulpea-db-build))"
Loading /Users/z/.config/emacs/init.el (source)...
Clearing removed files...
Clearing removed files...done
Processing modified files...

Symbol’s function definition is void: org-roam--org-roam-file-p
Run with ‘--debug’ (‘-d’) option to see error backtrace
make: *** [vulpea] Error 1`

Got this when I try to run most commands related to org-roam:

`Debugger entered--Lisp error: (void-function org-roam--org-roam-file-p)
  (org-roam--org-roam-file-p)
  (if (org-roam--org-roam-file-p) (progn (add-hook 'after-save-hook #'vino-db-update-file nil 'local)))
  vino-db--update-on-save-h()
  run-hooks(find-file-hook)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer inbox-qingshuis-mbp.lan.org> "~/Dropbox/vulpea/inbox-qingshuis-mbp.lan.org" nil nil "~/Dropbox/vulpea/inbox-qingshuis-mbp.lan.org" (43145720 16777221))
  find-file-noselect("/Users/z/Dropbox/vulpea/inbox-qingshuis-mbp.lan.or...")
  (let ((buf (find-file-noselect (progn (or (progn (and ... t)) (signal 'wrong-type-argument (list ... node))) (aref node 1))))) (save-current-buffer (set-buffer buf) (goto-char (progn (or (progn (and (memq ... cl-struct-org-roam-node-tags) t)) (signal 'wrong-type-argument (list 'org-roam-node node))) (aref node 7)))) buf)
  org-roam-node--find(#s(org-roam-node :file "/Users/z/Dropbox/vulpea/inbox-qingshuis-mbp.lan.or..." :file-hash nil :file-atime nil :file-mtime nil :id "a2e17783-830c-4d6a-8940-7b4c5c083187" :level 0 :point 1 :todo nil :priority nil :scheduled nil :deadline nil :title "LIFE" :properties (("CATEGORY" . "inbox-qingshuis-mbp.lan") ("ID" . "a2e17783-830c-4d6a-8940-7b4c5c083187") ("BLOCKED" . "") ("FILE" . "/Users/z/Dropbox/vulpea/inbox-qingshuis-mbp.lan.or...") ("PRIORITY" . "B")) :olp nil :tags ("project") :aliases nil :refs nil))
  (let ((buf (org-roam-node--find node))) (funcall (if other-window #'switch-to-buffer-other-window #'pop-to-buffer-same-window) buf))
  org-roam-node-visit(#s(org-roam-node :file "/Users/z/Dropbox/vulpea/inbox-qingshuis-mbp.lan.or..." :file-hash nil :file-atime nil :file-mtime nil :id "a2e17783-830c-4d6a-8940-7b4c5c083187" :level 0 :point 1 :todo nil :priority nil :scheduled nil :deadline nil :title "LIFE" :properties (("CATEGORY" . "inbox-qingshuis-mbp.lan") ("ID" . "a2e17783-830c-4d6a-8940-7b4c5c083187") ("BLOCKED" . "") ("FILE" . "/Users/z/Dropbox/vulpea/inbox-qingshuis-mbp.lan.or...") ("PRIORITY" . "B")) :olp nil :tags ("project") :aliases nil :refs nil) nil)
  (if (progn (or (progn (and (memq (type-of note) cl-struct-vulpea-note-tags) t)) (signal 'wrong-type-argument (list 'vulpea-note note))) (aref note 1)) (org-roam-node-visit (org-roam-node-from-id (progn (or (progn (and (memq ... cl-struct-vulpea-note-tags) t)) (signal 'wrong-type-argument (list 'vulpea-note note))) (aref note 1))) other-window) (if (not require-match) (progn (org-roam-capture- :node (record 'org-roam-node nil nil nil nil nil nil nil nil nil nil nil (progn (or (progn ...) (signal ... ...)) (aref note 4)) nil nil nil nil nil) :props '(:finalize find-file)))))
  (let* ((region-text (if (region-active-p) (progn (org-link-display-format (buffer-substring-no-properties (set-marker ... ...) (set-marker ... ...)))))) (note (vulpea-select "Note" :filter-fn (or filter-fn vulpea-find-default-filter) :require-match require-match :initial-prompt region-text))) (if (progn (or (progn (and (memq (type-of note) cl-struct-vulpea-note-tags) t)) (signal 'wrong-type-argument (list 'vulpea-note note))) (aref note 1)) (org-roam-node-visit (org-roam-node-from-id (progn (or (progn (and ... t)) (signal 'wrong-type-argument (list ... note))) (aref note 1))) other-window) (if (not require-match) (progn (org-roam-capture- :node (record 'org-roam-node nil nil nil nil nil nil nil nil nil nil nil (progn (or ... ...) (aref note 4)) nil nil nil nil nil) :props '(:finalize find-file))))))
  vulpea-find()
  funcall-interactively(vulpea-find)
  call-interactively(vulpea-find nil nil)
  command-execute(vulpea-find)`

Not sure whether you have this situation or not.
If you need any information let me know.

Best,
Qingshui

**Comment by d12frosted** [comment]
Hi @qingshuizheng 

Thanks for letting me know. Strangely, the [daily build passes][1]. I will investigate what's wrong. 

[1]: https://github.com/d12frosted/environment/runs/2881912065?check_suite_focus=true

**Comment by d12frosted** [comment]
I fixed that in [vino][1]. Though I am curious, why you noticed this during `eru install emacs` 🤔 

```emacs-lisp
(defun vulpea-db-build ()
  "Update notes database."
  (when (file-directory-p vulpea-directory)
    (org-roam-db-sync)))
```

This function is being called at the end of installation flow and it doesn't execute anything `vino` related (something I am actually going to change haha), because by default `vino` updates db only when something gots changed. Are you modifying files during db sync by chance?

[1]: https://github.com/d12frosted/vino/pull/100/commits/7a841b21ddb525195d3a70bfbb87af8f8156f799

**Comment by qingshuizheng** [comment]
> I fixed that in [vino](https://github.com/d12frosted/vino/pull/100/commits/7a841b21ddb525195d3a70bfbb87af8f8156f799). 

Hi @d12frosted , This is really to the rescue, run `M-x straight-pull-package vino`, and `eru install emacs` passes every step. Thanks for investigating.

> Are you modifying files during db sync by chance?

Not sure, haha.
I'm quite new to emacs and git, trials and errors, almost driven crazy.

Here are the few commits I made based on yours in case you want to have a look at them, [qingshuizheng/environment](https://github.com/qingshuizheng/environment/commits/master). 

Love to give feedback any time.

**Comment by qingshuizheng** [comment]
Hi @d12frosted,

Now that the main issue is solved, I'm gonna close it up.

Thanks for the time and effort put into this. 😀👌
