### ISSUE TITLE
vulpea-project-p issue saving buffers containing no TODO entries

### ISSUE THREAD

**Issue by danielclucas** [d12frosted/environment#23]
I have been using your work as an inspiration for building my own configuration. Building upon the work you shared about building a dynamic agenda, I made use of the updated `vulpea-project-p` function in lib-vulpea.el. I think I found a bug. 

I have also made use of your ensure-file-tags function and hooked it into the `pre-save-hook` for org-roam-files (I am not making full use of the vulpea library, at least not yet). However, when `vulpea-project-p` is called by `ensure-file-tags` in an org-roam-buffer that lacks any TODO entries and consists only of headlines without any body text then the line `goto-char (org-element-property :contents-begin h))` returns an error. In my use case, I am incorporating a calendar.org file into my agenda files that at the moment only consists of headline items without body text.

**Comment by danielclucas** [comment]
I looked into this further, and it seems that there is another related issue that `org-element-parse-buffer` with the `headline` granularity argument is generating a list of headlines which as elements do not contain inherited tags. So the `seq-contains-p` condition to catch "REFILE" tags is not triggering correctly. 

Later, when execution gets to the `goto-char` section it seems that the individual headlines in the parsed list of headlines are causing issues with the statement. 

It seems like this behavior isn't apparent except in edge cases. Does `vulpea-project-p` execute as expected for you in those cases where the presence of a 'REFILE' tag alone should trigger a non-nil return for a project file?

**Comment by d12frosted** [comment]
Hey @danielclucas . I am in the office right now and can't dig into your question. Just caught one things that I can comment on right away.

> do not contain inherited tags. So the seq-contains-p condition to catch "REFILE" tags is not triggering correctly.

What are you the values of `org-use-tag-inheritance` and `org-tags-exclude-from-inheritance`?

Will read in depth your questions later :)

**Comment by danielclucas** [comment]
Ah, @d12frosted no problem! I appreciate whatever help you can provide :)

My `org-use-tag-inheritance` is set to `t` and `org-tags-exclude-from-inheritance` is `("project" "people")`, which is part of why I am surprised that the filetags are appearing to not be inherited by the headings in the list generated by `org-element-parse-buffer`.

Thanks again for your help!

**Comment by d12frosted** [comment]
> Building upon the work you shared about building a dynamic agenda, I made use of the updated vulpea-project-p function in lib-vulpea.el. I think I found a bug.

Just for reference, you are talking about this function, right?

https://github.com/d12frosted/environment/blob/584e9d3061b9aa06eef0267d68e317c97f2b57bb/emacs/lisp/lib-vulpea.el#L64-L96

> that lacks any TODO entries and consists only of headlines without any body text

Does that mean that your headlines lack properties drawers as well? Can you please share example file? Cause I tried to reproduce it with the following file and haven't run into any problems.

```org
:PROPERTIES:
:ID:                     dcadee96-ea16-4b24-ab7a-78cc8abfe007
:END:
#+title: Some Title
#+filetags: :some-tag:

* One

* Two
```

---

> So the seq-contains-p condition to catch "REFILE" tags is not triggering correctly.

That's interesting. I have the following content in an org-mode buffer.

```
* Parent                                                             :REFILE:

** Child
```

And when I call `org-get-tags` while the point is on the line `** Child`, I get the following result

```emacs-lisp
(#("REFILE" 0 6 (inherited t cursor-sensor-functions (svg-tag--cursor-function) isearch-open-invisible org-fold-core--isearch-show isearch-open-invisible-temporary org-fold-core--isearch-show-temporary fontified t wrap-prefix "  " ...)))
```

But when I use `org-element` API I get different result.

```emacs-lisp
(org-element-map
      (org-element-parse-buffer 'headline)
      'headline
  (lambda (h)
    (message "%s :: %s"
             (org-element-property :raw-value h)
             (org-element-property :tags h))))
```

Running this code results in the following output:

```
Parent :: (REFILE)
Child :: nil
```

When I run `org-element-at-point` on child I get the following:

```
'(headline
  (:raw-value Child
   :begin 313
   :end 322
   :pre-blank 0
   :contents-begin nil
   :contents-end nil
   :robust-begin nil
   :robust-end nil
   :level 2
   :priority nil
   :tags nil
   :todo-keyword nil
   :todo-type nil
   :post-blank 0
   :footnote-section-p nil
   :archivedp nil
   :commentedp nil
   :post-affiliated 313
   :title Child
   :mode section
   :granularity element
   :cached t
   :parent (headline (:raw-value Parent
                      :begin 234
                      :end 322
                      :pre-blank 1
                      :contents-begin 313
                      :contents-end 322
                      :robust-begin 315
                      :robust-end 320
                      :level 1
                      :priority nil
                      :tags (REFILE)
                      :todo-keyword nil
                      :todo-type nil
                      :post-blank 0
                      :footnote-section-p nil
                      :archivedp nil
                      :commentedp nil
                      :post-affiliated 234
                      :title Parent
                      :mode nil
                      :granularity element
                      :cached t
                      :parent (org-data (:begin 1
                                         :contents-begin 1
                                         :contents-end 322
                                         :end 322
                                         :robust-begin 81
                                         :robust-end 320
                                         :post-blank 0
                                         :post-affiliated 1
                                         :path IRRELEVANT
                                         :mode org-data
                                         :ID IRRELEVANT
                                         :CATEGORY IRRELEVANT
                                         :cached t))))))
```

So I guess `org-element` API doesn't support tag inheritance. Which kind of makes sense, as it simply parses the structure. I don't have good solution at this point, but I thing you can use `org-get-tags`:

```
  ;; any headline with REFILE tag
- (seq-contains-p (org-element-property :tags h) "REFILE")
+ (seq-contains-p
+  (org-get-tags (org-element-property :contents-begin h))
+  "REFILE")
```

I haven't noticed this because I rarely have subheadings under REFILE headings and even when I do, I don't care about them at all in terms of tagging of the file containing this refile element.

So this tackles the tag issue, but I could not reproduce that error you get.

**Comment by danielclucas** [comment]
Yes, that was

**Comment by danielclucas** [comment]
Apologies, I pressed closed by accident.

**Comment by danielclucas** [comment]
That was the function I was referencing, yes. Your solution for the REFILE issue worked, so thank you for that. 

Here is an example org file that is causing the error. 
```
:PROPERTIES:
:ID:                     d883986c-c521-4862-ac26-20c6f51868bc
:END:
#+title: test
#+filetags: :some-tag:
* one
* two
```

The error occurs when execution of `mudra-project-p` gets to the line 
```(goto-char (org-element-property :contents-begin h))``` 

More specifically, `org-element-property` is returning 
```
Result: #2=(headline (:raw-value #1="one" :begin 119 :end 125 :pre-blank 0 :contents-begin nil :contents-end nil :robust-begin nil :robust-end nil :level 1 :priority nil :tags nil :todo-keyword nil :todo-type nil :post-blank 0 :footnote-section-p nil :archivedp nil :commentedp nil :post-affiliated 119 :title #1# :mode first-section :granularity headline :parent #4=(org-data (:begin 1 :contents-begin 1 :contents-end 131 :end 131 :robust-begin 81 :robust-end 129 :post-blank 0 :post-affiliated 1 ...)))))```
Sorry, I'm not sure how to run org-element-at-point and port the output to a readable format as you did (though if there's an easy way I would appreciate the advice on how to do that)

But as you can see the headline is being read as having a nil value for `contents-begin`, which is what is causing the error. 

I tried the same thing with your file with a parent and child, like so:
```
:PROPERTIES:
:ID:                     d883986c-c521-4862-ac26-20c6f51868bc
:END:
#+title: test
#+filetags: :some-tag:
* ones 
** two
```
Then I the parent node does not cause issue, but when execution gets to the child node "two" org-element is saying that its `contents-begin` value is nil. This might not be due to anything in your code, but at this point I have no idea where to even begin tracking down what is causing this issue.

**Comment by danielclucas** [comment]
After some more investigation, I am able to get the function to seemingly work without causing an error with the following modification:
```
- (goto-char (org-element-property :contents-begin h)) 
+ (goto-char (org-element-property :begin h)) 
```
It seems that in my case at least, org element is treating the headline as a greater element relative to its contents. So when there are no contents for the headlines `org-element-property` returns nil for `:contents-begin`. 

I tested this with TODOs that are on subheadings, and it functions as desired. I do wonder if you see any potential issues with this change? Looking over the logic that follows, I don't immediately see any issue.

**Comment by danielclucas** [comment]
Ah, now I understand! Thank you for the proper fix. Ironically, this all started while I was testing out the use of a separate calendar file for the purpose of tracking things like birthdays which had headlines with no content. 

I am still experimenting with my configuration, so it is nice to have the option to manage such things this way! 

One last thing, you say that for you property drawers are created for every headline on save. I have spent quite a bit of time reading through the vulpea related files in your environment but I missed where you generate this behavior. How did you set that up?

**Comment by d12frosted** [comment]
> Ironically, this all started while I was testing out the use of a separate calendar file for the purpose of tracking things like birthdays which had headlines with no content.

:joy_cat: amazing!

> One last thing, you say that for you property drawers are created for every headline on save. I have spent quite a bit of time reading through the vulpea related files in your environment but I missed where you generate this behavior. How did you set that up?

All required stuff is defined here:

https://github.com/d12frosted/environment/blob/e3e3bce762303922abbbceebf5a041e159392a2f/emacs/lisp/lib-vulpea-id.el#L42-L68

And used like this:

https://github.com/d12frosted/environment/blob/e3e3bce762303922abbbceebf5a041e159392a2f/emacs/lisp/init-vulpea.el#L226-L227

**Comment by danielclucas** [comment]
Great! Exactly what I needed!

**Comment by danielclucas** [comment]
Revisiting this conversation I am curious what benefits you derive from generating an ID for every heading? How do you avoid the great number of IDs from cluttering your org-roam queries?

**Comment by d12frosted** [comment]
@danielclucas good question. As far as I know there is no way to tell Org Roam to stop treating headings as notes. And TBH I dislike this. Why? Because in my use case headings are not separate notes. But I still need IDs for attachments and links (e.g. when I export file as PDF/HTML/whatever). Of course, you can assign ids only when needed (e.g. attach and link routine does that automatically), but for historical reasons I use automatic assignment everywhere. BTW, you can set `vulpea-id-auto-targets` to `file` only.

But you are right that it clutters Org Roam search. Luckily, I have Vulpea 😸 Instead of using Org Roam interactive functions, I use [`vulpea-select`][1]-based functions like [`vulpea-find`][2] with default filters:

```emacs-lisp
(setq vulpea-find-default-filter
      (lambda (note)
        (= (vulpea-note-level note) 0)))
```

With this configuration `vulpea-find` only displays file notes. You can use the same filter for `vulpea-insert` as well. I plan to optimise it even further by providing faster filter for this specific use-case, but functionality-wise, it helps me a lot to avoid clutter.

[1]: https://github.com/d12frosted/vulpea/tree/master#vulpea-select
[2]: https://github.com/d12frosted/vulpea/tree/master#filter-function

**Comment by danielclucas** [comment]
I see, thank you for clarifying that! I have used custom wrappers on Org Roam's search functions to filter, but it sounds like Vulpea makes this even more straightforward. I may try that out.
