### ISSUE TITLE
Non-existent agenda file when changing org-roam file names

### ISSUE THREAD

**Issue by danielclucas** [d12frosted/environment#27]
Hello,
When I change the name of an org-roam file that is building org-agenda and then rebuild the agenda I encounter the following error in the minibuffer
```lisp
Non-existent agenda file ~/.../file.org. [R]emove from list or [A]bort?
```
which I have to respond to before my agenda builds. I find that if I use `org-roam-db-sync` then this is taken care of.

I am curious if you have run into this, and if you have how you deal with it? If you haven't, what would you suggest? I was contemplating just adding `org-roam-db-sync` into the `post-save-hook`, but after looking through your code in both `vulpea` and in your environment, I don't see any such thing.

**Comment by d12frosted** [comment]
@danielclucas This happens when you have files in `org-agenda-files` that do not exist anymore. So that boils down to the question - do you update the value of `org-agenda-files` after renaming files? I suspect not, because you get this error 😄 

In my case, I just update the value of `org-agenda-files` _before_ agenda is built:

https://github.com/d12frosted/environment/blob/d9c1a3e342eb5c0dfc7fcf721fe50d3bfca1b90e/emacs/lisp/lib-vulpea-agenda.el#L80-L86

https://github.com/d12frosted/environment/blob/d9c1a3e342eb5c0dfc7fcf721fe50d3bfca1b90e/emacs/lisp/init-vulpea.el#L297

This approach is described in [this article][1], though it covers more stuff.

Hope that helps.

[1]: https://d12frosted.io/posts/2021-01-16-task-management-with-roam-vol5.html

**Comment by d12frosted** [comment]
Oh, and another comment. Since you say that running `org-roam-db-sync` solves the problem... Why don't you enable auto sync mode? Like, if you rely on information from `org-roam-db`, you should sync it after any change, otherwise you are risking to run into more issues.

**Comment by danielclucas** [comment]
@d12frosted Hmm, I do already employ the method you suggest with slight modifications for my personal situation:
```lisp
(defun organum-agenda-files-update (&rest _)
  "Update the value of `org-agenda-files'."
  (setq org-agenda-files (seq-uniq (append (list organum-agenda-inbox-file
                                                 organum-agenda-standalone-file
                                                 organum-agenda-someday-file)
                                           (organum-project-files)))))
```
and `organum-project-files` are defined as
```lisp
(defun organum-project-files ()
    "Return a list of note files containing 'agenda' tag." ;
    (seq-uniq
     (seq-map
      #'car
      (org-roam-db-query
       [:select [nodes:file]
        :from tags
        :left-join nodes
        :on (= tags:node-id nodes:id)
        :where (like tag (quote "%\"agenda\"%"))]))))
```
and in my `init-organum` file (I have borrowed a lot how you've structured your env :laughing:) I have in my `use-package` block of org-agenda:
```lisp
 :config
  (advice-add 'org-agenda :before #'organum-agenda-files-update)
```
However I still run into the issue. 

I have tried to enable org-roam-db-autosync mode in the same manner as you do:
```lisp
(use-package org-roam
  :defer t
  :commands (org-roam-db-autosync-enable
             org-roam-db-sync)
```
But for some reason it still doesn't enable on startup (value of org-roam-db-autosync-mode remains nil)! I am not sure what would be interfering with it.

**Comment by danielclucas** [comment]
After playing around with this more, I believe my initial diagnosis was off. It seems `org-agenda-files-update` works correctly when I use the `org-agenda` command. However, if I switch to the agenda buffer and use the agenda command '(r) rebuild agenda buffer' then I encounter the error. This is what I have been doing. This behavior is independent of whether or not I use `org-roam-db-sync`. So it would seem to be an issue with how the rebuild agenda buffer command works. 

The matter of my org-roam-db-autosync-mode not enabling is a separate issue.

**Comment by danielclucas** [comment]
After yet further investigation, I was able to get org-roam-db-autosync-mode enabled. I see that you actually enable it with this line in your org-roam use-package block
```elisp
(ignore-errors
    (org-roam-db-autosync-enable))
```
I am just curious why you use that to activate it as opposed to say `org-roam-db-autosync-mode +1` which as far as I can tell also works. 

But as to the original issue, I am still unclear about what the distinction is between calling the agenda and rebuilding the agenda buffer(s). Do you know if there is a way to get the (r) command to work without causing that issue? 

Thanks as usual for all of your help!

**Comment by danielclucas** [comment]
@d12frosted I realize at this point that this is an issue of how the `org-agenda` command works vs. `org-agenda-redo`/`org-agenda-redo-all` commands work. Everything based on your code works as intended, so I'm going to close this, as this is really a question of how I can get `org-agenda-redo`, which is the command triggered by using (r) in the agenda buffer, to take into account changes in my `org-agenda-files`. Thank you for your responses, they helped me get on the right track for resolving this. I will work on this some more in the proper channels.
